title:            TRTWN
description:      Describe your website here.
disqus_shortname: trtwn
reading_time:     true
words_per_minute: 200
url:              http://trtwn.de

# Owner/author information
owner:
  name:           Dennis Trautwein
  avatar:         avatar.jpg
  bio:            "BSc. in extraterrestrial physics | iOS Dev at Touchtech Wellington | WebDev at Sanctuary Digital in Melbourne | currently doing MSc. in solid state physics"
  email:          dennisauskiel@posteo.de
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:         dennis-tra
  stackexchange:  http://stackoverflow.com/users/3934265/graf
  linkedin:       dennis-trautwein-6a4307106
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_verify:
google_analytics:   UA-73454958-2
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .env.example
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - _posts/templates
  - spec
  - tmp
