# Docs: https://docs.docker.com/compose/compose-file/
version: '2'
services:
  trtwn-jekyll:
    build: .
    container_name: trtwn-jekyll
    env_file: .env
    ports:
      - 4000:4000
    volumes:
      - .:/app
